-- MySQL Script generated by MySQL Workbench
-- Fri May  8 14:03:02 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psm_seguros
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `psm_seguros` ;

-- -----------------------------------------------------
-- Schema psm_seguros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psm_seguros` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `psm_seguros` ;

-- -----------------------------------------------------
-- Table `psm_seguros`.`tipo_documento_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`tipo_documento_persona` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`tipo_documento_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`pais` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `abreviatura` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`estado_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`estado_departamento` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`estado_departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_departamento_pais_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_departamento_pais`
    FOREIGN KEY (`pais_id`)
    REFERENCES `psm_seguros`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`ciudad_municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`ciudad_municipio` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`ciudad_municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado_departamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_municipio_estado_departamento1_idx` (`estado_departamento_id` ASC),
  CONSTRAINT `fk_ciudad_municipio_estado_departamento1`
    FOREIGN KEY (`estado_departamento_id`)
    REFERENCES `psm_seguros`.`estado_departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`roles` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`estado_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`estado_usuario` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`estado_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `roles_id` INT NOT NULL,
  `estado_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_roles1_idx` (`roles_id` ASC),
  INDEX `fk_usuarios_estado_usuario1_idx` (`estado_usuario_id` ASC),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `psm_seguros`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_estado_usuario1`
    FOREIGN KEY (`estado_usuario_id`)
    REFERENCES `psm_seguros`.`estado_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`empleados` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `detalle_direccion` VARCHAR(45) NULL,
  `ciudad_municipio_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  INDEX `fk_empleados_ciudad_municipio1_idx` (`ciudad_municipio_id` ASC),
  INDEX `fk_empleados_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_empleados_ciudad_municipio1`
    FOREIGN KEY (`ciudad_municipio_id`)
    REFERENCES `psm_seguros`.`ciudad_municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `psm_seguros`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`tipo_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`tipo_persona` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`tipo_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`persona` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `tipo_persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_persona_tipo_persona1_idx` (`tipo_persona_id` ASC),
  CONSTRAINT `fk_persona_tipo_persona1`
    FOREIGN KEY (`tipo_persona_id`)
    REFERENCES `psm_seguros`.`tipo_persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`documento_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`documento_persona` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`documento_persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `tipo_documento_id` INT NOT NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documento_cliente_tipo_documento1_idx` (`tipo_documento_id` ASC),
  INDEX `fk_documento_cliente_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_documento_cliente_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `psm_seguros`.`tipo_documento_persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_cliente_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `psm_seguros`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`detalle_persona_natural`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`detalle_persona_natural` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`detalle_persona_natural` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_persona_natural_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_detalle_persona_natural_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `psm_seguros`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`detalle_persona_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`detalle_persona_juridica` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`detalle_persona_juridica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_persona_juridica_persona1_idx` (`persona_id` ASC),
  CONSTRAINT `fk_detalle_persona_juridica_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `psm_seguros`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`tipo_contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`tipo_contacto` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`tipo_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`persona_contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`persona_contacto` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`persona_contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  `tipo_contacto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_persona_contacto_persona1_idx` (`persona_id` ASC),
  INDEX `fk_persona_contacto_tipo_contacto1_idx` (`tipo_contacto_id` ASC),
  CONSTRAINT `fk_persona_contacto_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `psm_seguros`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_contacto_tipo_contacto1`
    FOREIGN KEY (`tipo_contacto_id`)
    REFERENCES `psm_seguros`.`tipo_contacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`tipo_servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`tipo_servicios` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`tipo_servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`aseguradora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`aseguradora` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`aseguradora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipo_servicios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aseguradora_tipo_servicios1_idx` (`tipo_servicios_id` ASC),
  CONSTRAINT `fk_aseguradora_tipo_servicios1`
    FOREIGN KEY (`tipo_servicios_id`)
    REFERENCES `psm_seguros`.`tipo_servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`persona_seguro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`persona_seguro` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`persona_seguro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `aseguradora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_persona_seguro_persona1_idx` (`persona_id` ASC),
  INDEX `fk_persona_seguro_aseguradora1_idx` (`aseguradora_id` ASC),
  CONSTRAINT `fk_persona_seguro_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `psm_seguros`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_seguro_aseguradora1`
    FOREIGN KEY (`aseguradora_id`)
    REFERENCES `psm_seguros`.`aseguradora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`tipo_documento_contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`tipo_documento_contrato` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`tipo_documento_contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`documentos_contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`documentos_contrato` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`documentos_contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_seguro_id` INT NOT NULL,
  `tipo_documento_contrato_id` INT NOT NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documentos_contrato_persona_seguro1_idx` (`persona_seguro_id` ASC),
  INDEX `fk_documentos_contrato_tipo_documento_contrato1_idx` (`tipo_documento_contrato_id` ASC),
  CONSTRAINT `fk_documentos_contrato_persona_seguro1`
    FOREIGN KEY (`persona_seguro_id`)
    REFERENCES `psm_seguros`.`persona_seguro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_contrato_tipo_documento_contrato1`
    FOREIGN KEY (`tipo_documento_contrato_id`)
    REFERENCES `psm_seguros`.`tipo_documento_contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`estado_comprobante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`estado_comprobante` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`estado_comprobante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`comprobante_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`comprobante_pago` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`comprobante_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_seguro_id` INT NOT NULL,
  `estado_comprobante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comprobante_pago_persona_seguro1_idx` (`persona_seguro_id` ASC),
  INDEX `fk_comprobante_pago_estado_comprobante1_idx` (`estado_comprobante_id` ASC),
  CONSTRAINT `fk_comprobante_pago_persona_seguro1`
    FOREIGN KEY (`persona_seguro_id`)
    REFERENCES `psm_seguros`.`persona_seguro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprobante_pago_estado_comprobante1`
    FOREIGN KEY (`estado_comprobante_id`)
    REFERENCES `psm_seguros`.`estado_comprobante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`estado_reclamo_contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`estado_reclamo_contrato` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`estado_reclamo_contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`reclamo_contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`reclamo_contrato` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`reclamo_contrato` (
  `id` INT NOT NULL,
  `persona_seguro_id` INT NOT NULL,
  `estado_reclamo_contrato_id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reclamo_contrato_persona_seguro1_idx` (`persona_seguro_id` ASC),
  INDEX `fk_reclamo_contrato_estado_reclamo_contrato1_idx` (`estado_reclamo_contrato_id` ASC),
  INDEX `fk_reclamo_contrato_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_reclamo_contrato_persona_seguro1`
    FOREIGN KEY (`persona_seguro_id`)
    REFERENCES `psm_seguros`.`persona_seguro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reclamo_contrato_estado_reclamo_contrato1`
    FOREIGN KEY (`estado_reclamo_contrato_id`)
    REFERENCES `psm_seguros`.`estado_reclamo_contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reclamo_contrato_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `psm_seguros`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`listado_beneficiarios_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`listado_beneficiarios_empresa` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`listado_beneficiarios_empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `persona_seguro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_listado_beneficiarios_empresa_persona_seguro1_idx` (`persona_seguro_id` ASC),
  CONSTRAINT `fk_listado_beneficiarios_empresa_persona_seguro1`
    FOREIGN KEY (`persona_seguro_id`)
    REFERENCES `psm_seguros`.`persona_seguro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`detalle_vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`detalle_vehiculo` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`detalle_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `n_placa` VARCHAR(45) NULL,
  `n_motor` VARCHAR(45) NULL,
  `n_chasis_grabado` VARCHAR(45) NULL,
  `n_vin` VARCHAR(45) NULL,
  `persona_seguro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dealle_vehiculo_persona_seguro1_idx` (`persona_seguro_id` ASC),
  CONSTRAINT `fk_dealle_vehiculo_persona_seguro1`
    FOREIGN KEY (`persona_seguro_id`)
    REFERENCES `psm_seguros`.`persona_seguro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psm_seguros`.`detalle_servicio_automotor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psm_seguros`.`detalle_servicio_automotor` ;

CREATE TABLE IF NOT EXISTS `psm_seguros`.`detalle_servicio_automotor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrada` DATETIME NULL,
  `fecha_entrega` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `monto` VARCHAR(45) NULL,
  `detalle_vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_servicio_automotor_detalle_vehiculo1_idx` (`detalle_vehiculo_id` ASC),
  CONSTRAINT `fk_detalle_servicio_automotor_detalle_vehiculo1`
    FOREIGN KEY (`detalle_vehiculo_id`)
    REFERENCES `psm_seguros`.`detalle_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
